# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: Open an issue
    url: https://github.com/Semarina/PocketDice/issues/new/choose
    about: Bug reports, feature requests, and ideas